project:
  type: website
  output-dir: "docs"

website:
  title: "Daniel Nyakwela | Research & Analysis"
  navbar:
    background: "#0d6efd"
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portifolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/DaNI-26-W
      - icon: linkedin
        href: https://www.linkedin.com/in/Daniel-Nyakwela
format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: _footer.qmd

