project:
  type: website
  output-dir: "docs"

website:
  title: "Daniel Kadoke Nyakwela"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portifolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css


